steps:
  # Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vyntra-web'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg' 
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_KEY}'
      - '.'

  # Push de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vyntra-web']

  # Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'vyntra-web'
      - '--image=gcr.io/$PROJECT_ID/vyntra-web'
      - '--region=us-central1'
      - '--platform=managed'
      - '--set-env-vars=NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_KEY}'

# Variables de sustitución (configurar en Cloud Build Trigger)
substitutions:
  _SUPABASE_URL: 'https://pkavalqnlhcwzglaeehf.supabase.co'
  _SUPABASE_KEY: '' # Dejar vacío, se configura en el trigger

# Configuración de logging para evitar errores
options:
  logging: CLOUD_LOGGING_ONLY 