steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vyntra-web', '.']
    secretEnv: ['EMAILJS_CONFIG']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vyntra-web']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'vyntra-web'
      - '--image=gcr.io/$PROJECT_ID/vyntra-web'
      - '--region=us-central1'
      - '--platform=managed'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/emailjs-config/versions/latest
    env: 'EMAILJS_CONFIG' 